apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "habit-tracker.fullname" . }}
data:
  application.properties: |
    spring.application.name={{ .Values.config.springApplicationName }}
    server.port={{ .Values.config.serverPort }}
    spring.mvc.problemdetails.enabled={{ .Values.config.problemDetailsEnabled }}